apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
helmCharts:
  - name: redis
    releaseName: redis
    version: 20.3.0
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      namespaceOverride: redis
      # limitador doesn't currently support redis HA with sentinel or cluster mode
      # NOTE: for cluster mode a different chart must be used (https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster)
      architecture: standalone
      global:
        compatibility:
          openshift:
            adaptSecurityContext: force
