apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # Install an instance of kube-state-metrics specificly for gateway & kaudrant metrics
  - kube-state-metrics.yaml

